author: "站点作者"
description: "站点一句话简介"

# 是否输出全文 RSS
feedFull: true

# 页脚链接（可自由增删）
footerLinks:
  - name: GitHub
    url:  https://github.com/you
    icon: github.svg
  - name: Feed
    url:  /feed.xml
    icon: rss.svg
  - name: License
    url:  /about/#license
    